twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['user/layout/form_theme.html.twig']
    globals:
        organisatienaam: '%env(ORGNAAM)%'
        organisatiemail: '%env(ORGMAIL)%'
        forumlink: '%env(FORUMLINK)%'
        orgnaamkort: '%env(ORGNAAMKORT)'
        organisatiewebsite: '%env(ORGURL)%'
