twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['user/layout/form_theme.html.twig']
    globals:
        organisatienaam: '%env(ORGANIZATION_NAME)%'
        orgnaamkort: '%env(ORGANIZATION_NAME_SHORT)%'
        organisatiewebsite: '%env(HOMEPAGE)%'
        orgLogo: '%env(ORG_LOGO)%'
