version: '3'

networks:
  nginx-php74-mysql8-node:

services:

  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php74-service
      - mariadb10-service
    networks:
      - nginx-php74-mysql8-node

  # php
  php74-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php74-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
    networks:
      - nginx-php74-mysql8-node

  # mysql
  mariadb10-service:
    image: mariadb:10
    container_name: mariadb10-container
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: trotzalledem
    networks:
      - nginx-php74-mysql8-node

  # node
  node-service:
    image: node:latest
    container_name: node-container
    volumes:
      - ./app:/var/www/project
    working_dir: /var/www/project
    networks:
      - nginx-php74-mysql8-node
