version: '3'

networks:
  mijnrood:

services:

  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php74-service
      - mariadb10-service
    networks:
      - mijnrood

  # php
  php74-service:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php74-container
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/project
    networks:
      - mijnrood

  # mysql
  mariadb10-service:
    image: mariadb:10
    container_name: mariadb10-container
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: trotzalledem
    networks:
      - mijnrood

  # node
  node-service:
    image: node:latest
    container_name: node-container
    volumes:
      - .:/var/www/project
    working_dir: /var/www/project
    networks:
      - mijnrood
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
    command: "npm run watch"

  mailcatcher:
    image: sj26/mailcatcher:v0.8.1
    ports:
      - "1080:1080"
    networks:
      - mijnrood
