contribution:
  tiers:
    - amount: 900
      description: Studenten en werklozen
    - amount: null
      description: "Werkenden: 0,5% van het netto inkomen (minimaal €15 per kwartaal)"
signup:
  min_age: 16
  max_age: null

mollie_payment_description: "Contributiebetaling {{organisation_name}}, voor lidnummer {{member_number}}"
