contribution:
  tiers:
    - amount: 750
      description: Minimum
    - amount: 1500
      description: Basis
    - amount: 2500
      description: Minder
    - amount: 3500
      description: Gemiddeld
    - amount: 5000
      description: Hoog
    - amount: 10000
      description: Heel hoog
    - amount: null
      description: ik betaal een andere contributie, namelijk:
signup:
  min_age: 14
  max_age: 27

mollie_payment_description: "Contributiebetaling {{organisation_name}}, voor lidnummer {{member_number}}"
